import {
  User,
  MemberProfile,
  MembershipPlan,
  AttendanceRecord,
  WorkoutPlan,
  NutritionPlan,
  PaymentRecord,
  ProductItem,
  SecurityAuditLog,
  SystemNotification,
  DashboardKPIs,
} from './types';

export const INITIAL_KPIS: DashboardKPIs = {
  activeMembers: 342,
  totalMembers: 410,
  todayAttendance: 84,
  monthlyRevenue: 28450,
  weeklyRevenue: 7120,
  outstandingPayments: 1450,
  expiringMemberships: 12,
  churnRate: 2.1,
  retentionRate: 97.9,
};

export const MOCK_USERS: Record<string, User> = {
  admin: {
    id: 'usr-admin-1',
    email: 'alex.admin@apexfitness.com',
    name: 'Alex Vance',
    role: 'ADMIN',
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    phone: '+1 (555) 019-2834',
    bio: 'Founder & Managing Director of Apex Fitness Club.',
    createdAt: '2025-01-10',
  },
  manager: {
    id: 'usr-mgr-1',
    email: 'sarah.mgr@apexfitness.com',
    name: 'Sarah Jenkins',
    role: 'MANAGER',
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    phone: '+1 (555) 012-9843',
    bio: 'Operations Manager overseeing staff & billing.',
    createdAt: '2025-02-01',
  },
  trainer: {
    id: 'usr-trn-1',
    email: 'marcus.trainer@apexfitness.com',
    name: 'Marcus Stone',
    role: 'TRAINER',
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    phone: '+1 (555) 014-4920',
    bio: 'Head Strength Coach & NASM Certified Personal Trainer.',
    createdAt: '2025-02-15',
  },
  receptionist: {
    id: 'usr-rec-1',
    email: 'elena.rec@apexfitness.com',
    name: 'Elena Rostova',
    role: 'RECEPTIONIST',
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    phone: '+1 (555) 018-3829',
    bio: 'Front Desk Lead & Member Experience Specialist.',
    createdAt: '2025-03-01',
  },
  member: {
    id: 'usr-mem-1',
    email: 'david.chen@gmail.com',
    name: 'David Chen',
    role: 'MEMBER',
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    phone: '+1 (555) 011-7722',
    bio: 'Avid powerlifter targeting a 500lb deadlift.',
    createdAt: '2025-04-12',
  },
};

export const MOCK_MEMBERSHIP_PLANS: MembershipPlan[] = [
  {
    id: 'plan-basic',
    name: 'Standard Monthly',
    description: 'Full gym access, standard locker room & cardio deck.',
    durationMonths: 1,
    price: 59,
    type: 'MONTHLY',
    features: ['Full Gym Access', 'Locker Room Access', 'Free Wi-Fi', 'Basic Mobile App Pass'],
    isActive: true,
  },
  {
    id: 'plan-quarterly',
    name: 'Quarterly Athlete',
    description: '3 months full access with complimentary sauna & body scans.',
    durationMonths: 3,
    price: 159,
    type: 'QUARTERLY',
    features: ['Full Gym Access', 'Sauna & Recovery Lounge', '1 InBody Scan / Month', 'Guest Pass x2'],
    isPopular: true,
    isActive: true,
  },
  {
    id: 'plan-vip',
    name: 'VIP All-Access Annual',
    description: 'Ultimate membership with 24/7 keycard, unlimited classes & personal trainer session.',
    durationMonths: 12,
    price: 599,
    type: 'VIP',
    features: ['24/7 Keycard Access', 'Unlimited Group Classes', 'Monthly PT Assessment', 'Towel Service', '15% Off Pro Shop'],
    isActive: true,
  },
  {
    id: 'plan-pt-pkg',
    name: 'Personal Training Bundle',
    description: '10 1-on-1 personal training sessions with a Master Coach.',
    durationMonths: 1,
    price: 450,
    type: 'PERSONAL_TRAINING',
    features: ['10x 1-on-1 Sessions', 'Custom AI Meal Plan', 'Weekly Body Composition Analysis', 'Direct Trainer Chat'],
    isActive: true,
  },
];

export const MOCK_MEMBERS: MemberProfile[] = [
  {
    id: 'mem-1',
    userId: 'usr-mem-1',
    user: MOCK_USERS.member,
    gender: 'Male',
    dob: '1994-06-15',
    heightCm: 178,
    weightKg: 82.5,
    targetWeightKg: 78.0,
    fitnessGoal: 'Hypertrophy & Strength',
    medicalNotes: 'Mild lower back stiffness on heavy deadlifts.',
    emergencyContactName: 'Lisa Chen',
    emergencyContactPhone: '+1 (555) 019-9922',
    qrCode: 'APEX-MEMBER-7722',
    joinDate: '2025-04-12',
    membership: {
      id: 'm-sub-1',
      memberId: 'mem-1',
      planId: 'plan-quarterly',
      plan: MOCK_MEMBERSHIP_PLANS[1],
      startDate: '2026-06-01',
      endDate: '2026-09-01',
      status: 'ACTIVE',
      autoRenew: true,
      pricePaid: 159,
    },
  },
  {
    id: 'mem-2',
    userId: 'usr-mem-2',
    user: {
      id: 'usr-mem-2',
      email: 'emily.watson@yahoo.com',
      name: 'Emily Watson',
      role: 'MEMBER',
      status: 'ACTIVE',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
      phone: '+1 (555) 013-8833',
      createdAt: '2025-05-10',
    },
    gender: 'Female',
    dob: '1998-11-03',
    heightCm: 165,
    weightKg: 59.0,
    targetWeightKg: 56.0,
    fitnessGoal: 'Marathon Preparation & Lean Muscle',
    medicalNotes: 'None',
    emergencyContactName: 'Tom Watson',
    emergencyContactPhone: '+1 (555) 012-3344',
    qrCode: 'APEX-MEMBER-8833',
    joinDate: '2025-05-10',
    membership: {
      id: 'm-sub-2',
      memberId: 'mem-2',
      planId: 'plan-vip',
      plan: MOCK_MEMBERSHIP_PLANS[2],
      startDate: '2026-01-15',
      endDate: '2027-01-15',
      status: 'ACTIVE',
      autoRenew: true,
      pricePaid: 599,
    },
  },
  {
    id: 'mem-3',
    userId: 'usr-mem-3',
    user: {
      id: 'usr-mem-3',
      email: 'robert.taylor@techcorp.io',
      name: 'Robert Taylor',
      role: 'MEMBER',
      status: 'ACTIVE',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80',
      phone: '+1 (555) 017-4499',
      createdAt: '2025-06-20',
    },
    gender: 'Male',
    dob: '1988-02-28',
    heightCm: 183,
    weightKg: 91.2,
    targetWeightKg: 84.0,
    fitnessGoal: 'Weight Loss & Endurance',
    medicalNotes: 'Asthma - carries inhaler',
    emergencyContactName: 'Karen Taylor',
    emergencyContactPhone: '+1 (555) 018-5511',
    qrCode: 'APEX-MEMBER-4499',
    joinDate: '2025-06-20',
    membership: {
      id: 'm-sub-3',
      memberId: 'mem-3',
      planId: 'plan-basic',
      plan: MOCK_MEMBERSHIP_PLANS[0],
      startDate: '2026-07-05',
      endDate: '2026-08-05',
      status: 'ACTIVE',
      autoRenew: false,
      pricePaid: 59,
    },
  },
  {
    id: 'mem-4',
    userId: 'usr-mem-4',
    user: {
      id: 'usr-mem-4',
      email: 'sophia.martinez@gmail.com',
      name: 'Sophia Martinez',
      role: 'MEMBER',
      status: 'ACTIVE',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80',
      phone: '+1 (555) 016-1188',
      createdAt: '2025-08-01',
    },
    gender: 'Female',
    dob: '1995-09-12',
    heightCm: 170,
    weightKg: 64.0,
    targetWeightKg: 62.0,
    fitnessGoal: 'Tone & Functional Fitness',
    emergencyContactName: 'Carlos Martinez',
    emergencyContactPhone: '+1 (555) 016-9900',
    qrCode: 'APEX-MEMBER-1188',
    joinDate: '2025-08-01',
    membership: {
      id: 'm-sub-4',
      memberId: 'mem-4',
      planId: 'plan-pt-pkg',
      plan: MOCK_MEMBERSHIP_PLANS[3],
      startDate: '2026-07-20',
      endDate: '2026-08-20',
      status: 'ACTIVE',
      autoRenew: true,
      pricePaid: 450,
    },
  },
  {
    id: 'mem-5',
    userId: 'usr-mem-5',
    user: {
      id: 'usr-mem-5',
      email: 'james.wilson@outlook.com',
      name: 'James Wilson',
      role: 'MEMBER',
      status: 'SUSPENDED',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=300&q=80',
      phone: '+1 (555) 019-3322',
      createdAt: '2025-03-14',
    },
    gender: 'Male',
    dob: '1991-04-05',
    heightCm: 175,
    weightKg: 80.0,
    qrCode: 'APEX-MEMBER-3322',
    joinDate: '2025-03-14',
    membership: {
      id: 'm-sub-5',
      memberId: 'mem-5',
      planId: 'plan-basic',
      plan: MOCK_MEMBERSHIP_PLANS[0],
      startDate: '2026-05-01',
      endDate: '2026-06-01',
      status: 'EXPIRED',
      autoRenew: false,
      pricePaid: 59,
    },
  },
];

export const MOCK_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-101',
    userId: 'usr-mem-1',
    userName: 'David Chen',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    userRole: 'MEMBER',
    checkInTime: '2026-08-02 08:14 AM',
    method: 'QR_CODE',
  },
  {
    id: 'att-102',
    userId: 'usr-mem-2',
    userName: 'Emily Watson',
    userAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    userRole: 'MEMBER',
    checkInTime: '2026-08-02 09:30 AM',
    method: 'QR_CODE',
  },
  {
    id: 'att-103',
    userId: 'usr-mem-3',
    userName: 'Robert Taylor',
    userAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80',
    userRole: 'MEMBER',
    checkInTime: '2026-08-02 10:05 AM',
    method: 'RECEPTIONIST',
    verifiedBy: 'Elena Rostova',
  },
  {
    id: 'att-104',
    userId: 'usr-mem-4',
    userName: 'Sophia Martinez',
    userAvatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80',
    userRole: 'MEMBER',
    checkInTime: '2026-08-02 10:42 AM',
    method: 'BARCODE',
  },
];

export const MOCK_WORKOUTS: WorkoutPlan[] = [
  {
    id: 'wp-1',
    title: 'Hypertrophy Upper Body Power',
    description: 'Heavy compound push-pull routine focusing on chest, back, and shoulders.',
    level: 'INTERMEDIATE',
    goal: 'Muscle Mass',
    isTemplate: true,
    createdBy: 'Marcus Stone',
    assignedToName: 'David Chen',
    exercises: [
      { id: 'ex-1', name: 'Barbell Bench Press', category: 'Strength', muscleGroup: 'Chest', equipment: 'Barbell', sets: 4, reps: '8-10', restSeconds: 90, instructions: 'Keep shoulder blades retracted, touch chest with bar smoothly.' },
      { id: 'ex-2', name: 'Barbell Bent-Over Row', category: 'Strength', muscleGroup: 'Back', equipment: 'Barbell', sets: 4, reps: '8-10', restSeconds: 90, instructions: 'Maintain 45 degree hip hinge, pull bar to belly button.' },
      { id: 'ex-3', name: 'Seated Dumbbell Overhead Press', category: 'Strength', muscleGroup: 'Shoulders', equipment: 'Dumbbells', sets: 3, reps: '10-12', restSeconds: 60, instructions: 'Press fully overhead without arching lower back.' },
      { id: 'ex-4', name: 'Cable Lateral Raise', category: 'Hypertrophy', muscleGroup: 'Shoulders', equipment: 'Cable', sets: 4, reps: '12-15', restSeconds: 45, instructions: 'Slight bend in elbows, raise to shoulder height.' },
    ],
    createdAt: '2026-07-01',
  },
  {
    id: 'wp-2',
    title: 'Functional Core & Lower Body Burn',
    description: 'High tempo leg press, lunges, and core stability circuits for athletic agility.',
    level: 'BEGINNER',
    goal: 'Tone & Agility',
    isTemplate: true,
    createdBy: 'Marcus Stone',
    assignedToName: 'Sophia Martinez',
    exercises: [
      { id: 'ex-5', name: 'Goblet Squats', category: 'Strength', muscleGroup: 'Legs', equipment: 'Kettlebell', sets: 3, reps: '12-15', restSeconds: 60, instructions: 'Deep squat posture, keep chest upright.' },
      { id: 'ex-6', name: 'Walking Dumbbell Lunges', category: 'Endurance', muscleGroup: 'Quads / Glutes', equipment: 'Dumbbells', sets: 3, reps: '12 per leg', restSeconds: 60, instructions: 'Control knee lowering, push off front heel.' },
      { id: 'ex-7', name: 'Hanging Leg Raises', category: 'Core', muscleGroup: 'Abs', equipment: 'Pull-up Bar', sets: 3, reps: '15', restSeconds: 45, instructions: 'Control movement without swinging.' },
    ],
    createdAt: '2026-07-15',
  },
];

export const MOCK_NUTRITION_PLANS: NutritionPlan[] = [
  {
    id: 'nut-1',
    title: 'Lean Muscle Recomp (2,800 kcal)',
    assignedToName: 'David Chen',
    createdBy: 'Marcus Stone',
    dailyCalories: 2800,
    proteinGrams: 210,
    carbsGrams: 310,
    fatGrams: 76,
    mealCategories: [
      {
        title: 'Breakfast',
        time: '07:30 AM',
        meals: [
          { name: 'Oatmeal with Whey Protein, Banana & Blueberries', portion: '2 cups oatmeal, 1 scoop whey, fruit', calories: 620, protein: 42, carbs: 96, fat: 8 },
          { name: 'Whole Eggs & Egg Whites Scramble', portion: '2 whole eggs + 3 whites', calories: 250, protein: 26, carbs: 2, fat: 15 },
        ],
      },
      {
        title: 'Lunch',
        time: '01:00 PM',
        meals: [
          { name: 'Grilled Chicken Breast with Jasmine Rice & Broccoli', portion: '220g chicken, 2 cups rice', calories: 760, protein: 52, carbs: 108, fat: 12 },
        ],
      },
      {
        title: 'Post-Workout Shake',
        time: '05:30 PM',
        meals: [
          { name: 'ISO-Whey Isolate + Large Banana & Dextrose', portion: '2 scoops whey, 1 large banana', calories: 370, protein: 46, carbs: 42, fat: 3 },
        ],
      },
      {
        title: 'Dinner',
        time: '08:00 PM',
        meals: [
          { name: 'Salmon Filet with Sweet Potato & Asparagus', portion: '220g salmon, 300g sweet potato', calories: 800, protein: 44, carbs: 62, fat: 38 },
        ],
      },
    ],
    createdAt: '2026-07-10',
  },
];

export const MOCK_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay-501',
    userId: 'usr-mem-2',
    userName: 'Emily Watson',
    userEmail: 'emily.watson@yahoo.com',
    membershipPlanName: 'VIP All-Access Annual',
    amount: 599.00,
    paymentMethod: 'CARD',
    status: 'COMPLETED',
    invoiceNumber: 'INV-2026-00891',
    description: 'Annual VIP Renewal Fee',
    date: '2026-08-01 10:14 AM',
  },
  {
    id: 'pay-502',
    userId: 'usr-mem-1',
    userName: 'David Chen',
    userEmail: 'david.chen@gmail.com',
    membershipPlanName: 'Quarterly Athlete',
    amount: 159.00,
    paymentMethod: 'CARD',
    status: 'COMPLETED',
    invoiceNumber: 'INV-2026-00892',
    description: 'Quarterly Membership Subscription',
    date: '2026-07-28 02:45 PM',
  },
  {
    id: 'pay-503',
    userId: 'usr-mem-4',
    userName: 'Sophia Martinez',
    userEmail: 'sophia.martinez@gmail.com',
    membershipPlanName: 'Personal Training Bundle',
    amount: 450.00,
    paymentMethod: 'CASH',
    status: 'COMPLETED',
    invoiceNumber: 'INV-2026-00893',
    description: '10x PT Sessions Package',
    date: '2026-07-20 11:30 AM',
  },
  {
    id: 'pay-504',
    userId: 'usr-mem-3',
    userName: 'Robert Taylor',
    userEmail: 'robert.taylor@techcorp.io',
    membershipPlanName: 'Standard Monthly',
    amount: 59.00,
    paymentMethod: 'RECURRING',
    status: 'PENDING',
    invoiceNumber: 'INV-2026-00894',
    description: 'Monthly Automated Renewal',
    date: '2026-08-02 09:00 AM',
  },
];

export const MOCK_PRODUCTS: ProductItem[] = [
  {
    id: 'prod-1',
    name: 'Optimum Whey Isolate (Chocolate 2kg)',
    category: 'SUPPLEMENT',
    sku: 'SUP-WHEY-CHO-01',
    price: 64.99,
    costPrice: 42.00,
    stockQuantity: 28,
    minStockLevel: 10,
    supplier: 'NutriFit Wholesale',
  },
  {
    id: 'prod-2',
    name: 'Pre-Workout Energy Burst (Sour Apple)',
    category: 'SUPPLEMENT',
    sku: 'SUP-PRE-APP-02',
    price: 39.99,
    costPrice: 22.50,
    stockQuantity: 4, // Low stock trigger
    minStockLevel: 8,
    supplier: 'NutriFit Wholesale',
  },
  {
    id: 'prod-3',
    name: 'ElectroHydrate Ion Sports Drink 500ml',
    category: 'DRINK',
    sku: 'DRK-ELE-500-03',
    price: 3.50,
    costPrice: 1.20,
    stockQuantity: 120,
    minStockLevel: 25,
    supplier: 'AquaSport Beverages',
  },
  {
    id: 'prod-4',
    name: 'Apex Fitness Seamless Gym Towel',
    category: 'MERCHANDISE',
    sku: 'MER-TWL-BLK-04',
    price: 18.00,
    costPrice: 7.50,
    stockQuantity: 45,
    minStockLevel: 15,
    supplier: 'Apex Apparel Inc.',
  },
  {
    id: 'prod-5',
    name: 'Lifting Wrist Straps Heavy-Duty',
    category: 'EQUIPMENT',
    sku: 'EQP-STP-RED-05',
    price: 14.99,
    costPrice: 5.00,
    stockQuantity: 2, // Low stock trigger
    minStockLevel: 5,
    supplier: 'IronGrip Gear',
  },
];

export const MOCK_NOTIFICATIONS: SystemNotification[] = [
  {
    id: 'notif-1',
    title: 'Membership Expiring Soon',
    message: 'Member Robert Taylor membership expires in 3 days.',
    type: 'MEMBERSHIP',
    isRead: false,
    createdAt: '10 min ago',
  },
  {
    id: 'notif-2',
    title: 'New Payment Received',
    message: 'Emily Watson paid $599.00 for VIP All-Access Annual.',
    type: 'PAYMENT',
    isRead: false,
    createdAt: '1 hour ago',
  },
  {
    id: 'notif-3',
    title: 'Inventory Alert',
    message: 'Pre-Workout Energy Burst is below minimum threshold (4 left).',
    type: 'SYSTEM',
    isRead: true,
    createdAt: '3 hours ago',
  },
];

export const MOCK_AUDIT_LOGS: SecurityAuditLog[] = [
  {
    id: 'log-1',
    userEmail: 'alex.admin@apexfitness.com',
    userRole: 'ADMIN',
    action: 'UPDATE_ROLE',
    entity: 'User Permissions',
    details: 'Promoted Elena Rostova to Head Receptionist.',
    ipAddress: '192.168.1.45',
    createdAt: '2026-08-02 11:04 AM',
  },
  {
    id: 'log-2',
    userEmail: 'elena.rec@apexfitness.com',
    userRole: 'RECEPTIONIST',
    action: 'CHECK_IN',
    entity: 'Attendance',
    details: 'Verified manual check-in for member Robert Taylor.',
    ipAddress: '192.168.1.52',
    createdAt: '2026-08-02 10:05 AM',
  },
  {
    id: 'log-3',
    userEmail: 'marcus.trainer@apexfitness.com',
    userRole: 'TRAINER',
    action: 'CREATE_WORKOUT',
    entity: 'WorkoutPlan',
    details: 'Created "Hypertrophy Upper Body Power" for David Chen.',
    ipAddress: '192.168.1.88',
    createdAt: '2026-08-01 04:20 PM',
  },
];

export const REVENUE_CHART_DATA = [
  { month: 'Jan', revenue: 21500, recurring: 18000, pos: 3500 },
  { month: 'Feb', revenue: 23200, recurring: 19200, pos: 4000 },
  { month: 'Mar', revenue: 25400, recurring: 20800, pos: 4600 },
  { month: 'Apr', revenue: 24800, recurring: 20200, pos: 4600 },
  { month: 'May', revenue: 26900, recurring: 21500, pos: 5400 },
  { month: 'Jun', revenue: 27800, recurring: 22100, pos: 5700 },
  { month: 'Jul', revenue: 28450, recurring: 22800, pos: 5650 },
];

export const ATTENDANCE_HEATMAP_DATA = [
  { day: 'Mon', morning: 42, afternoon: 68, evening: 95 },
  { day: 'Tue', morning: 38, afternoon: 60, evening: 88 },
  { day: 'Wed', morning: 45, afternoon: 72, evening: 102 },
  { day: 'Thu', morning: 40, afternoon: 64, evening: 86 },
  { day: 'Fri', morning: 48, afternoon: 80, evening: 92 },
  { day: 'Sat', morning: 65, afternoon: 75, evening: 40 },
  { day: 'Sun', morning: 50, afternoon: 45, evening: 25 },
];
